title: Wendi Chen
logo: /assets/img/photo.jpg
description: Hi, I'm Wendi Chen and you can call me Andy.
 I'm now a sophomore from SJTU, majoring in Computer Science.
 I'll share the techniques or projects I worked on in recent days on this page.
show_downloads: false
google_analytics: G-DFKCQGVMZS
theme: jekyll-theme-minimal
